${toc}

```{r setup, echo = FALSE, include = F}
library(knitr)
library(yaml)
library(tidyverse)
library(bigrquery)
library(magrittr)

config <- read_yaml("config.yaml")
round  <- "2"
src <- "fastq"
CURRENT_TEAM <- config$team

source("markdown_functions.R")
source("plot_functions.R")
source("query_functions.R")

knitr::read_chunk("knitr_chunks.R")

```

```{r validation2, echo = FALSE, include = F}
```
# Peptide binding predicted vs measured

Shown below is the comparison of predicted and measured binding values for your team's peptides.

For a given patient, the absence of a plot implies none of your teams predicted neoepitopes for that patient were validated.

## Patient 10
```{r echo = F, warning=F, fig.width = 20, fig.height = 10}
text <- make_scatterplot("10", scatterplot_df)
```
`r text`

## Patient 12
```{r echo = F, warning=F, fig.width = 20, fig.height = 10}
text <- make_scatterplot("12", scatterplot_df)
```
`r text`

## Patient 16
```{r echo = F, warning=F, fig.width = 20, fig.height = 10}
text <- make_scatterplot("16", scatterplot_df)
```
`r text`
