${toc}

```{r setup, echo = FALSE, include = F}
library(knitr)
library(yaml)
library(tidyverse)
library(bigrquery)
library(magrittr)
library(plotly)

config <- read_yaml("config.yaml")
round  <- "1"
CURRENT_TEAM <- config$team

source("markdown_functions.R")
source("plot_functions.R")
source("query_functions.R")

validation_dbi <- DBI::dbConnect(bigquery(), project = "neoepitopes", dataset = "Version_2") %>% 
    dplyr::tbl("Validated_bindings") %>% 
    dplyr::filter(!is.na(LJI_BINDING)) %>% 
    dplyr::mutate(LOG_MEASURED_BINDING = log10(LJI_BINDING + 1)) %>%
    dplyr::rename(PATIENT_ID = PATIENT) %>%
    dplyr::select(ALT_EPI_SEQ, HLA_ALLELE, PATIENT_ID, LOG_MEASURED_BINDING) %>% 
    dplyr::mutate(TEAM = "Measured")

# validation_dbi <- DBI::dbConnect(bigquery(), project = "neoepitopes", dataset = "Version_3") %>% 
#     dplyr::tbl("Validated_bindings") %>% 
#     dplyr::filter(!is.na(LJI_BINDING)) %>% 
#     dplyr::mutate(LOG_MEASURED_BINDING = log10(LJI_BINDING + 1))  %>% 
#     dplyr::select(ALT_EPI_SEQ, HLA_ALLELE, PATIENT_ID, LOG_MEASURED_BINDING)
#     dplyr::mutate(TEAM = "Measured")

prediction_dbi <- make_prediction_dbi_for_validation_plots(round) 
    

team_prediction_df <- prediction_dbi %>% 
    dplyr::filter(TEAM == CURRENT_TEAM) %>% 
    dplyr::select(
        PATIENT_ID, 
        HLA_ALLELE, 
        ALT_EPI_SEQ,
        TEAM, 
        LOG_PREDICTED_BINDING) %>% 
    dplyr::mutate(TEAM = "Your team") %>% 
    dplyr::as_tibble() %>% 
    dplyr::mutate(HLA_ALLELE = stringr::str_remove_all(HLA_ALLELE, "[:punct:]"))  # remove !!!!

validation_df <- validation_dbi %>% 
    dplyr::as_tibble() %>% 
    dplyr::mutate(PATIENT_ID = str_remove_all(PATIENT_ID, "Patient_"))

validated_epitope_df <- 
    inner_join(
        team_prediction_df, 
        validation_df, 
        by = c("PATIENT_ID", "HLA_ALLELE", "ALT_EPI_SEQ")) %>% 
    dplyr::select(PATIENT_ID, HLA_ALLELE, ALT_EPI_SEQ) %>% 
    dplyr::distinct()


scatterplot_df <- 
    dplyr::inner_join(
        team_prediction_df,
        validation_df,
        by = c("HLA_ALLELE", "ALT_EPI_SEQ", "PATIENT_ID"))

team_patients <- scatterplot_df %>%
    magrittr::use_series(PATIENT_ID) %>%
    unique() %>%
    sort

patient_dfs <- scatterplot_df %>%
    dplyr::group_by(PATIENT_ID) %>%
    dplyr::group_split() %>%
    magrittr::set_names(team_patients)


```
# Peptide binding predicted vs measured

Shown below is the comparison of predicted and measured binding values for your team's peptides.

For a given patient, the absence of a plot implies none of your teams predicted neoepitopes for that patient were validated.

## Patient 1
```{r echo = F, warning=F, fig.width = 20, fig.height = 10}
text <- make_scatterplot("1")
```
`r text`

## Patient 2
```{r echo = F, warning=F, fig.width = 20, fig.height = 10}
text <- make_scatterplot("2")
```
`r text`

## Patient 3
```{r echo = F, warning=F, fig.width = 20, fig.height = 10}
text <- make_scatterplot("3")
```
`r text`

## Patient 4
```{r echo = F, warning=F, fig.width = 20, fig.height = 10}
text <- make_scatterplot("4")
```
`r text`